spring.application.name=saga-res

# ===============================
# DATABASE
# ===============================
spring.datasource.url=jdbc:postgresql://db.zzvxrnhsvujhwcjjrhrn.supabase.co:5432/postgres?sslmode=require
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false


spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

# ===============================
# FLYWAY
# ===============================
spring.flyway.enabled=true

# ===============================
# JWT
# ===============================
security.jwt.issuer=saga-res
security.jwt.access-token-ttl=1h
security.jwt.secret=${JWT_SECRET}
